services:
  # PostgreSQL Database
  - type: pserv
    name: educatio-db
    env: postgres
    plan: free # ou starter para produção
    databaseName: educatio
    user: educatio_user

  # API Web Service
  - type: web
    name: educatio-api
    env: node
    plan: free # ou starter para produção
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true # Render gerará automaticamente
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: educatio-db
          property: connectionString
